# Header
menu:                      # Links in the navigation bar
  主页: /
  文档: /docs
  归档: /archives
  关于: /about
rss: /atom.xml

home:
  style: default           # default, detail

favicon:                   # Path to the custom favicon relative to /source (e.g. "/favicon.png" if your favicon file is located at /source/favicon.png)

# Banner
banner:
  enable: true                  # Display banner
  url: medias/banner_sao.jpg                          # Path to the banner image relative to /source. Web url is also supported
  position: center               # Specifies the alignment of the image, see the "object-position" property in CSS
  onAllPages: true               # Display banner on all pages instead of only the home page

# Appearance
hue: 250                         # The hue of the theme color (e.g. red: 0, orange: 60, blue: 260, purple: 300, pink: 345)
                                 # Visit `saicaca.github.io/vivia-preview` to preview the theme color

# Personal info
avatar: medias/icon.jpeg                            # Path to the avatar image relative to /source
author: CosmoLau
subtitle: 啥也不会的卑微程序员
links:
  - name: Email
    icon: fa-solid fa-envelope
    url: mailto:cosmolau@qq.com
  - name: Bilibili
    icon: fa-brands fa-bilibili    # Find icon codes at https://fontawesome.com/search
    url: https://space.bilibili.com/2260014
  - name: Steam
    icon: fa-brands fa-steam
    url: https://steamcommunity.com/id/CosmoLau/
  - name: GitHub
    icon: fa-brands fa-github
    url: https://github.com/CosmoLau

# Sidebar
sidebar:
  widgets:                 # Plugins to be enabled (profile, category, tag, archive, recent_posts)
    normal:                # Scroll along with the page
      - profile
    sticky:                # Stick to the top of the page
      - category
      - tag
      - archive
      - recent_posts

# Sidebar Widget behavior
archive_type: 'monthly'
recent_posts_limits: 5
categories:
  max_depth: 2             # Maximum depth of categories displayed in the widget (null for unlimited)

# Third-party comment system
comment:
  valine:
    enable: false         # Enable Valine comment system
    appId: 
    appKey: 
    placeholder: Just go go
    pageSize: 10
    highlight: true
    serverURLs: 
    # Other supported parameters can be added here if needed
    # Visit https://valine.js.org/configuration.html for more details
  twikoo:
    enable: false          # Enable Twikoo comment system
    envID:
    region:
    path: location.pathname
    lang:
    # See also: https://github.com/imaegoo/twikoo

#Analytics
gauges_analytics: false
google_analytics: true #UA-xxxxxx
baidu_analytics: true # ddxxxxxxxxxxxxxxxxx In the https://hm.baidu.com/hm.js? Afterwards

archive_generator:
  per_page: 0